trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.14.2'
  displayName: 'Instalando o Node.js 16.14.2...'

- script: |
    npm install -g yarn
  displayName: 'Instalando o Yarn...'
  
- script: |
    yarn && npm run publish
  displayName: 'Executando o build...'

- task: CopyFiles@2
  displayName: 'Copiando os arquivos compilados (/dist) para o diretório de compactação...'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/dist/'
    Contents: '**'
    TargetFolder: '$(Build.BinariesDirectory)'

- task: ArchiveFiles@2
  displayName: 'Compactando os arquivos gerados durante o build...'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/b'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)-$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publicando os artefatos de build...'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.DefinitionName)-$(Build.BuildId).zip'
    ArtifactName: '$(Build.DefinitionName)-$(Build.BuildId).zip'
    publishLocation: 'Container'

